In [4]:
students <- data.frame(
  Student_ID=c("S001","S002","S003","S004","S005","S006","S007","S007"),
  Programming_Grade=c(88,72,91,78,65,85,74,82),
  Math_Grade=c(85,70,88,80,68,90,73,79),
  Attendance=c(92,80,95,88,70,91,76,85),
  Prerequisite=c("Yes","No","Yes","Yes","No","Yes","No","Yes")
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S007       82                79         85         Yes

2. Explore the Data

In [8]:
summary(students)

nrow(students)
ncol(students)
cat("Attendance:",max(students$Attendance))
max(students$Math_Grade)
max(students$Programming_Grade)

     Student_ID Programming_Grade   Math_Grade      Attendance
 Length   :8    Min.   :65.00     Min.   :68.00   Min.   :70.00
 N.unique :7    1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 N.blank  :0    Median :80.00     Median :79.50   Median :86.50
 Min.nchar:4    Mean   :79.38     Mean   :79.12   Mean   :84.62
 Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
                Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

[1] 8

[1] 5

Attendance 95

[1] 90

[1] 91

3. Enter a Student ID

In [38]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S001
[1] "S001"

4. Search the Data Frame

In [39]:
student <- students[
  students$Student_ID == student_id,
]

student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

5. Check if the Students Exist

In [35]:
if (nrow(student) > 0){
  print("Student Found")
} else{
  print("Student Not Found")
}

student

[1] "Student Not Found"

     Student_ID Programming_Grade Math_Grade Attendance Prerequisite

6. Extract Student Information

In [48]:
student_id <- student$Student_ID
programming <- student$Programming_Grade
math <- student$Math_Grade
attendance <- student$Attendance
prerequisite <- student$Prerequisite

cat("Student ID:", student_id)
cat("\nProgramming Grade:", programming)
cat("\nMath Grade:", math)
cat("\nAttendance:", attendance)
cat("\nPrerequisite:", prerequisite)

Student ID: S001
Programming Grade: 88
Math Grade: 85
Attendance: 92
Prerequisite: Yes

7. Implement Rules

In [65]:
student_eligibility <- function(programming, math, attendance, prerequisite)
if (programming >= 80 && math >= 75 && attendance >= 80 && prerequisite == "Yes"){
  print("Eligible")
}else if (programming >= 75 && math >= 70 && attendance >= 75){
  print("Conditionally Eligible")
}else{
 print("Not Eligible")
}

student_eligibility(78,87,54,"No")

[1] "Not Eligible"

8. Apply the function to all Students

In [66]:
students$Eligibility <- mapply(
  student_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Conditionally Eligible"
[1] "Not Eligible"
[1] "Eligible"
[1] "Not Eligible"
[1] "Eligible"

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S007       82                79         85         Yes
  Eligibility            Recommendation
1 Eligible               Student may Enroll
2 Not Eligible           Complete requirements before enrollment
3 Eligible               Student may Enroll
4 Conditionally Eligible Complete requirements before enrollment
5 Not Eligible           Complete requirements before enrollment
6 Eligible               Student may Enroll
7 Not Eligible           Complete requirements before enrollment
8 Eligible               Student may Enroll

9. Create Recommendation Rules

In [69]:
get_recommendation <- function(eligibility) {

  if (eligibility == "Eligible") {
    return("Student may Enroll")

  } else if (eligibility == "Conditionally Eligible") {
    return("Consult Academic Adviser")

  } else {
    return("Complete requirements before enrollment")
  }
}

students$Recommendation <- sapply(
  students$Eligibility,
  get_recommendation
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S007       82                79         85         Yes
  Eligibility            Recommendation
1 Eligible               Student may Enroll
2 Not Eligible           Complete requirements before enrollment
3 Eligible               Student may Enroll
4 Conditionally Eligible Consult Academic Adviser
5 Not Eligible           Complete requirements before enrollment
6 Eligible               Student may Enroll
7 Not Eligible           Complete requirements before enrollment
8 Eligible               Student may Enroll

10. Expected Output

In [70]:
student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$Student_ID == student_id, ]

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", student$Programming_Grade, "\n")
  cat("Math Grade:", student$Math_Grade, "\n")
  cat("Attendance:", student$Attendance, "%\n")
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S004

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S004

Programming Grade: 78
Math Grade: 80
Attendance: 88 %
Prerequisite: Yes

Enrollment Status:
Conditionally Eligible

Recommendation:
Consult Academic Adviser
========================================